<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Locale / Language
    |--------------------------------------------------------------------------
    |
    | Sets the language used in UI texts generated by ptah (base-crud stubs,
    | view labels from CrudConfigGenerator).
    | Supported values: 'en' (default), 'pt_BR'.
    |
    | force_locale: when true, Ptah overrides the host application's APP_LOCALE.
    | Leave false (default) to avoid breaking Carbon, validation messages and
    | other packages that depend on the application locale.
    |
    */
    'force_locale' => env('PTAH_FORCE_LOCALE', false),
    'locale' => env('PTAH_LOCALE', 'en'),

    /*
    |--------------------------------------------------------------------------
    | Theme colors
    |--------------------------------------------------------------------------
    |
    | Brand palette for the whole Ptah UI (BaseCrud, Forge components, modules).
    | Set these once and everything follows — Ptah injects them as CSS custom
    | properties (`--color-primary`, `--ptah-primary`, …) in the layout <head>,
    | and ptah-components.css derives every tint/ring/hover from them via
    | color-mix(). No need to publish or edit any view, and it survives
    | `composer update`.
    |
    | Accepts any CSS color (hex, rgb, hsl, oklch). Override per project via
    | .env (PTAH_COLOR_PRIMARY=#0d9488) or here.
    |
    */
    'theme' => [
        'colors' => [
            'primary' => env('PTAH_COLOR_PRIMARY', '#5b21b6'),
            'success' => env('PTAH_COLOR_SUCCESS', '#10b981'),
            'danger' => env('PTAH_COLOR_DANGER', '#ef4444'),
            'warn' => env('PTAH_COLOR_WARN', '#f59e0b'),
            'dark' => env('PTAH_COLOR_DARK', '#1e293b'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | File Generation Paths
    |--------------------------------------------------------------------------
    |
    | Defines the directories where each file type will be generated by the
    | ptah:make command. All paths are relative to the application directory.
    |
    */
    'paths' => [
        'models' => app_path('Models'),
        'services' => app_path('Services'),
        'repositories' => app_path('Repositories'),
        'dtos' => app_path('DTOs'),
        'actions' => app_path('Actions'),
        'livewire' => app_path('Livewire'),
        'requests' => app_path('Http/Requests'),
        'resources' => app_path('Http/Resources'),
        'controllers' => app_path('Http/Controllers'),
        'views' => resource_path('views'),
    ],

    /*
    |--------------------------------------------------------------------------
    | User Preferences
    |--------------------------------------------------------------------------
    |
    | Defines the driver used to store user preferences.
    | Supported drivers: database
    |
    */
    'preferences' => [
        'driver' => 'database',
        'cache' => true,
        'ttl' => 3600,
    ],

    /*
    |--------------------------------------------------------------------------
    | API
    |--------------------------------------------------------------------------
    */
    'api' => [
        'prefix' => 'api',
        'middleware' => ['api', 'auth:sanctum'],
        'docs' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Ptah Forge — Component System
    |--------------------------------------------------------------------------
    |
    | Ptah Forge design system settings.
    |
    | prefix       : Blade component prefix (<x-forge-button>, etc.)
    | tailwind     : TailwindCSS version used in components
    | sidebar_items: sidebar items generated by scaffold
    |
    */
    'forge' => [
        'prefix' => 'forge',
        'tailwind' => 'v4',
        'sidebar_items' => [
            // Use Boxicons (bx) or FontAwesome (fas/far/fab) CSS classes:
            // ['label' => 'Dashboard', 'url' => '/dashboard', 'icon' => 'bx bx-home-alt',  'match' => 'dashboard'],
            // ['label' => 'Users',     'url' => '/users',     'icon' => 'bx bx-user',       'match' => 'users*'],
            // ['label' => 'Products',  'url' => '/products',  'icon' => 'bx bx-cube',       'match' => 'products*'],
            // ['label' => 'Settings',  'url' => '/settings',  'icon' => 'bx bx-cog',        'match' => 'settings*'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Scaffold
    |--------------------------------------------------------------------------
    */
    'scaffold' => [
        'layout' => 'forge-dashboard',
        'auth_layout' => 'forge-auth',
    ],

    /*
    |--------------------------------------------------------------------------
    | BaseCrud
    |--------------------------------------------------------------------------
    |
    | Settings for the BaseCrud system generated by ptah:forge.
    |
    */
    'crud' => [
        'cache_enabled' => true,
        'cache_ttl' => 3600,
        'per_page' => 25,
        'soft_deletes' => true,
        'confirm_delete' => true,

        /*
        | Who may open/save the in-app CRUD configuration editor.
        |
        | When the permissions module is ACTIVE, editing is always restricted to
        | master users or an explicit 'crud.config' manage grant (this flag is
        | ignored). When the module is OFF, the editor is DENIED by default —
        | set PTAH_CONFIG_EDITOR=true to opt back in. See ptah_can_manage_config().
        */
        'config_editor' => env('PTAH_CONFIG_EDITOR', false),

        /*
        | Namespaces a class-based lifecycle hook (@Class::method in CrudConfig)
        | may live under. A hook class outside these prefixes is refused — so a
        | crafted config can't instantiate arbitrary classes. Short hook names
        | resolve under the first entry.
        */
        'hook_namespaces' => ['App\\CrudHooks'],

        /*
        | Overrides/extends the built-in pt-BR label dictionary used by ptah:forge
        | and ptah:config when deriving colsNomeLogico from a column name.
        | Keys = column name (lowercase, without a trailing _id). Example:
        |   'observacoes' => 'Observações', 'valor_total' => 'Valor Total'
        */
        'label_dictionary' => [],
    ],

    /*
    |--------------------------------------------------------------------------
    | Export (async / large volume)
    |--------------------------------------------------------------------------
    |
    | Settings for the queued BaseCrud export (Fase 3 — "grande volume"). The
    | component still resolves the filtered/sorted ids; the queued job only
    | generates the file from those ids (same source of truth as the
    | synchronous export). Opt-in per CRUD via exportConfig.asyncExport.enabled.
    |
    | disk           : filesystem disk where generated files are stored.
    | path           : directory (within the disk) where files are written.
    | ttl_hours       : how long a generated file stays downloadable before
    |                   ptah:export-prune considers it expired.
    | async_max_rows : caps the number of ids collected for the queued job
    |                  (0 = unlimited; PDF still degrades to exportConfig.maxRows).
    */
    'export' => [
        'disk' => env('PTAH_EXPORT_DISK', 'local'),
        'path' => env('PTAH_EXPORT_PATH', 'ptah-exports'),
        'ttl_hours' => (int) env('PTAH_EXPORT_TTL_HOURS', 48),
        'async_max_rows' => (int) env('PTAH_EXPORT_ASYNC_MAX_ROWS', 0),
    ],

    /*
    |--------------------------------------------------------------------------
    | Optional Modules
    |--------------------------------------------------------------------------
    | Use `php artisan ptah:module {auth|menu|company|permissions|api|ai_agent}` to install each module.
    */
    'modules' => [
        'auth' => env('PTAH_MODULE_AUTH', false),
        'menu' => env('PTAH_MODULE_MENU', false),
        'company' => env('PTAH_MODULE_COMPANY', false),
        'permissions' => env('PTAH_MODULE_PERMISSIONS', false),
        'api' => env('PTAH_MODULE_API', false),
        'ai_agent' => env('PTAH_MODULE_AI_AGENT', false),
    ],

    /*
    |--------------------------------------------------------------------------
    | Auth Module
    |--------------------------------------------------------------------------
    */
    'auth' => [
        'guard' => 'web',
        'home' => '/dashboard',
        'register_enabled' => false,
        'two_factor' => true,
        'remember_me' => true,
        'session_protection' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Menu Module
    |--------------------------------------------------------------------------
    | driver 'config' uses sidebar_items (default, non-breaking).
    | driver 'database' reads from the menus table.
    */
    'menu' => [
        'driver' => env('PTAH_MENU_DRIVER', 'database'),
        'cache' => true,
        'cache_ttl' => 300,
        'max_depth' => 4,
    ],

    /*
    |--------------------------------------------------------------------------
    | Company Module
    |--------------------------------------------------------------------------
    | Company / branch management.
    | logo_disk / logo_path: where logos are stored.
    | address_fields: fields available in the address JSON.
    |
    | Note: the model (Ptah\Models\Company) and table (ptah_companies) are fixed —
    | the package references them directly. To add behaviour, extend the model in
    | your app; the table name is not configurable.
    */
    'company' => [
        'logo_disk' => env('PTAH_LOGO_DISK', 'public'),
        'logo_path' => env('PTAH_LOGO_PATH', 'company-logos'),
        'address_fields' => [
            'street', 'number', 'complement', 'district',
            'city', 'state', 'zip_code', 'country',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Permissions Module
    |--------------------------------------------------------------------------
    | Hierarchical access control system:
    | Company → Role (is_master = full bypass) → Page → Object → CRUD
    |
    | cache               : enables permission caching (highly recommended)
    | cache_ttl           : TTL in seconds
    | user_model          : host application's User model (no hard-coded FK)
    | user_id_field       : User model primary key field
    | user_query_scope    : optional Scope class to filter users shown in the
    |                       Permissions screen (e.g. only admin users)
    | company_session_key : session key for active company/branch
    | user_session_key    : session key for user id (apps without standard auth)
    | audit               : log accesses to the ptah_permission_audits table
    | audit_denied        : also log denied accesses
    | audit_master        : log accesses from users with MASTER role
    | multi_company       : user can have roles in multiple companies
    | allow_guest         : if false, guests always return false
    | admin_name          : name of the admin user created by the seeder
    | admin_email         : admin user e-mail
    | admin_password      : initial admin password (change after first login!)
    */
    'permissions' => [
        'cache' => env('PTAH_PERMISSION_CACHE', true),
        'cache_ttl' => (int) env('PTAH_PERMISSION_CACHE_TTL', 3600),
        'user_model' => env('PTAH_USER_MODEL', 'App\Models\User'),
        'user_id_field' => env('PTAH_USER_ID_FIELD', 'id'),
        // Optional Eloquent scope class applied to the user query in the
        // Permissions screen. Use this to restrict which users appear
        // (e.g. show only admin users in a project that has multiple user types).
        // Must implement \Illuminate\Database\Eloquent\Scope.
        // Example: 'user_query_scope' => App\Scopes\AdminUsersScope::class
        'user_query_scope' => env('PTAH_USER_QUERY_SCOPE', null),
        'company_session_key' => env('PTAH_COMPANY_SESSION_KEY', 'ptah_company_id'),
        'user_session_key' => env('PTAH_USER_SESSION_KEY', null),
        'audit' => env('PTAH_PERMISSION_AUDIT', false),
        'audit_denied' => env('PTAH_PERMISSION_AUDIT_DENIED', true),
        'audit_master' => env('PTAH_PERMISSION_AUDIT_MASTER', false),
        'multi_company' => env('PTAH_MULTI_COMPANY', true),
        'allow_guest' => env('PTAH_PERMISSION_ALLOW_GUEST', false),
        'admin_name' => env('PTAH_ADMIN_NAME', 'Administrador'),
        'admin_email' => env('PTAH_ADMIN_EMAIL', 'admin@admin.com'),
        // Initial admin password. Leave PTAH_ADMIN_PASSWORD unset to have a strong
        // random password generated and shown ONCE during installation. There is
        // intentionally no insecure hardcoded fallback. Always change it on first login.
        'admin_password' => env('PTAH_ADMIN_PASSWORD'),
    ],

    /*
    |--------------------------------------------------------------------------
    | AI Agent Module
    |--------------------------------------------------------------------------
    | Conversational AI widget powered by prism-php/prism.
    |
    | system_prompt          : default prompt injected into every conversation.
    | max_history            : max number of recent messages (per conversation) sent
    |                          as context — older ones are dropped. NOTE: this is a
    |                          message count, not a token count; very long messages
    |                          can still approach the model's context window.
    | rate_limit             : max requests per minute (per user when authenticated,
    |                          per session for guests).
    | stream                 : when true (default), the widget streams the answer
    |                          token-by-token; set false to wait for the full reply.
    | daily_token_limit      : optional per-user daily token ceiling. 0 disables it.
    | allow_guests           : when false (default), the chat widget is only available
    |                          to authenticated users.
    | expose_system_details  : when false (default), the built-in getSystemInfo tool
    |                          hides framework/PHP versions and the environment name.
    | tools                  : array of AiToolInterface classes to register globally.
    |                          Example: [\App\AI\Tools\MyCustomTool::class]
    |
    | Requires: composer require prism-php/prism
    | Enable  : php artisan ptah:module ai_agent
    */
    'ai_agent' => [
        'system_prompt' => env('PTAH_AI_SYSTEM_PROMPT', 'You are a helpful assistant.'),
        'max_history' => (int) env('PTAH_AI_MAX_HISTORY', 20),
        'rate_limit' => (int) env('PTAH_AI_RATE_LIMIT', 30),
        'stream' => (bool) env('PTAH_AI_STREAM', true),
        'daily_token_limit' => (int) env('PTAH_AI_DAILY_TOKEN_LIMIT', 0),
        'allow_guests' => (bool) env('PTAH_AI_ALLOW_GUESTS', false),
        'expose_system_details' => (bool) env('PTAH_AI_EXPOSE_SYSTEM_DETAILS', false),
        'tools' => [],
    ],

];
