<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Locale / Language
    |--------------------------------------------------------------------------
    |
    | Sets the language used in UI texts generated by ptah (base-crud stubs,
    | view labels from CrudConfigGenerator).
    | Supported values: 'en' (default), 'pt_BR'.
    |
    | force_locale: when true, Ptah overrides the host application's APP_LOCALE.
    | Leave false (default) to avoid breaking Carbon, validation messages and
    | other packages that depend on the application locale.
    |
    */
    'force_locale' => env('PTAH_FORCE_LOCALE', false),
    'locale'       => env('PTAH_LOCALE', 'en'),

    /*
    |--------------------------------------------------------------------------
    | Caminhos de geração de arquivos
    |--------------------------------------------------------------------------
    |
    | Define os diretórios onde cada tipo de arquivo será gerado pelo comando
    | ptah:make. Todos os caminhos são relativos ao diretório da aplicação.
    |
    */
    'paths' => [
        'models'       => app_path('Models'),
        'services'     => app_path('Services'),
        'repositories' => app_path('Repositories'),
        'dtos'         => app_path('DTOs'),
        'actions'      => app_path('Actions'),
        'livewire'     => app_path('Livewire'),
        'requests'     => app_path('Http/Requests'),
        'resources'    => app_path('Http/Resources'),
        'controllers'  => app_path('Http/Controllers'),
        'views'        => resource_path('views'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Sistema de preferências de usuário
    |--------------------------------------------------------------------------
    |
    | Define o driver para armazenamento de preferências de usuário.
    | Drivers disponíveis: database
    |
    */
    'preferences' => [
        'driver' => 'database',
        'cache'  => true,
        'ttl'    => 3600,
    ],

    /*
    |--------------------------------------------------------------------------
    | API
    |--------------------------------------------------------------------------
    */
    'api' => [
        'prefix'     => 'api',
        'middleware' => ['api', 'auth:sanctum'],
        'docs'       => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Ptah Forge — Sistema de Componentes
    |--------------------------------------------------------------------------
    |
    | Configurações do design system Ptah Forge.
    |
    | prefix    : prefixo dos componentes Blade (<x-forge-button>, etc.)
    | tailwind  : versão do TailwindCSS usada nos componentes
    | sidebar_items: itens da sidebar gerada pelo scaffold
    |
    */
    'forge' => [
        'prefix'        => 'forge',
        'tailwind'      => 'v4',
        'sidebar_items' => [
            // Use classes CSS Boxicons (bx) ou FontAwesome (fas/far/fab):
            // ['label' => 'Dashboard',    'url' => '/dashboard', 'icon' => 'bx bx-home-alt',  'match' => 'dashboard'],
            // ['label' => 'Usuários',     'url' => '/users',     'icon' => 'bx bx-user',      'match' => 'users*'],
            // ['label' => 'Produtos',     'url' => '/products',  'icon' => 'bx bx-cube',      'match' => 'products*'],
            // ['label' => 'Configurações','url' => '/settings',  'icon' => 'bx bx-cog',       'match' => 'settings*'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Scaffold
    |--------------------------------------------------------------------------
    */
    'scaffold' => [
        'layout'    => 'forge-dashboard',
        'auth_layout' => 'forge-auth',
    ],

    /*
    |--------------------------------------------------------------------------
    | BaseCrud
    |--------------------------------------------------------------------------
    |
    | Configurações do sistema BaseCrud gerado pelo ptah:forge.
    |
    */
    'crud' => [
        'cache_enabled'  => true,
        'cache_ttl'      => 3600,
        'per_page'       => 25,
        'soft_deletes'   => true,
        'confirm_delete' => true,
        'export_driver'  => 'excel',
    ],

    /*
    |--------------------------------------------------------------------------
    | Módulos opcionais
    |--------------------------------------------------------------------------
    | Use `php artisan ptah:module {auth|menu|company|permissions|api}` para instalar cada módulo.
    */
    'modules' => [
        'auth'        => env('PTAH_MODULE_AUTH', false),
        'menu'        => env('PTAH_MODULE_MENU', false),
        'company'     => env('PTAH_MODULE_COMPANY', false),
        'permissions' => env('PTAH_MODULE_PERMISSIONS', false),
        'api'         => env('PTAH_MODULE_API', false),
    ],

    /*
    |--------------------------------------------------------------------------
    | Módulo Auth
    |--------------------------------------------------------------------------
    */
    'auth' => [
        'guard'               => 'web',
        'home'                => '/dashboard',
        'register_enabled'    => false,
        'two_factor'          => true,
        'remember_me'         => true,
        'session_protection'  => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Módulo Menu
    |--------------------------------------------------------------------------
    | driver 'config' usa sidebar_items (padrão, não quebra nada).
    | driver 'database' lê da tabela menus.
    */
    'menu' => [
        'driver'    => env('PTAH_MENU_DRIVER', 'config'),
        'cache'     => true,
        'cache_ttl' => 300,
        'max_depth' => 4,
    ],

    /*
    |--------------------------------------------------------------------------
    | Módulo Company
    |--------------------------------------------------------------------------
    | Gerenciamento de empresas/filiais.
    | logo_disk / logo_path: onde os logos são armazenados.
    | address_fields: campos disponíveis no JSON de endereço.
    */
    'company' => [
        'model'          => \Ptah\Models\Company::class,
        'table'          => 'ptah_companies',
        'logo_disk'      => env('PTAH_LOGO_DISK', 'public'),
        'logo_path'      => env('PTAH_LOGO_PATH', 'company-logos'),
        'address_fields' => [
            'street', 'number', 'complement', 'district',
            'city', 'state', 'zip_code', 'country',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Módulo Permissions
    |--------------------------------------------------------------------------
    | Sistema de controle de acesso hierárquico:
    | Empresa → Perfil/Role (is_master = bypass total) → Página → Objeto → CRUD
    |
    | cache          : habilita cache de permissões (altamente recomendado)
    | cache_ttl      : TTL em segundos
    | user_model     : model User da aplicação host (sem FK hard-coded)
    | user_id_field  : campo PK do model User
    | company_session_key : chave da session para empresa/filial ativa
    | user_session_key    : chave de session para user id (apps sem auth padrão)
    | audit          : gravar log de acessos na tabela ptah_permission_audits
    | audit_denied   : gravar também acessos negados
    | audit_master   : gravar acessos de usuários com role MASTER
    | multi_company  : usuário pode ter roles em múltiplas empresas
    | allow_guest    : se false, guests sempre retornam false
    | admin_name     : nome do usuário admin criado no seeder
    | admin_email    : e-mail do usuário admin
    | admin_password : senha inicial do admin (alterar após primeiro login!)
    */
    'permissions' => [
        'cache'               => env('PTAH_PERMISSION_CACHE', true),
        'cache_ttl'           => (int) env('PTAH_PERMISSION_CACHE_TTL', 3600),
        'user_model'          => env('PTAH_USER_MODEL', 'App\Models\User'),
        'user_id_field'       => env('PTAH_USER_ID_FIELD', 'id'),
        'company_session_key' => env('PTAH_COMPANY_SESSION_KEY', 'ptah_company_id'),
        'user_session_key'    => env('PTAH_USER_SESSION_KEY', null),
        'audit'               => env('PTAH_PERMISSION_AUDIT', false),
        'audit_denied'        => env('PTAH_PERMISSION_AUDIT_DENIED', true),
        'audit_master'        => env('PTAH_PERMISSION_AUDIT_MASTER', false),
        'multi_company'       => env('PTAH_MULTI_COMPANY', true),
        'allow_guest'         => env('PTAH_PERMISSION_ALLOW_GUEST', false),
        'admin_name'          => env('PTAH_ADMIN_NAME', 'Administrador'),
        'admin_email'         => env('PTAH_ADMIN_EMAIL', 'admin@admin.com'),
        // No default password — must be set via PTAH_ADMIN_PASSWORD in .env.
        // The seeder will throw a RuntimeException if this is not configured.
        'admin_password'      => env('PTAH_ADMIN_PASSWORD'),
    ],

];
