<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Locale / Language
    |--------------------------------------------------------------------------
    |
    | Sets the language used in UI texts generated by ptah (base-crud stubs,
    | view labels from CrudConfigGenerator).
    | Supported values: 'en' (default), 'pt_BR'.
    |
    | force_locale: when true, Ptah overrides the host application's APP_LOCALE.
    | Leave false (default) to avoid breaking Carbon, validation messages and
    | other packages that depend on the application locale.
    |
    */
    'force_locale' => env('PTAH_FORCE_LOCALE', false),
    'locale'       => env('PTAH_LOCALE', 'en'),

    /*
    |--------------------------------------------------------------------------
    | File Generation Paths
    |--------------------------------------------------------------------------
    |
    | Defines the directories where each file type will be generated by the
    | ptah:make command. All paths are relative to the application directory.
    |
    */
    'paths' => [
        'models'       => app_path('Models'),
        'services'     => app_path('Services'),
        'repositories' => app_path('Repositories'),
        'dtos'         => app_path('DTOs'),
        'actions'      => app_path('Actions'),
        'livewire'     => app_path('Livewire'),
        'requests'     => app_path('Http/Requests'),
        'resources'    => app_path('Http/Resources'),
        'controllers'  => app_path('Http/Controllers'),
        'views'        => resource_path('views'),
    ],

    /*
    |--------------------------------------------------------------------------
    | User Preferences
    |--------------------------------------------------------------------------
    |
    | Defines the driver used to store user preferences.
    | Supported drivers: database
    |
    */
    'preferences' => [
        'driver' => 'database',
        'cache'  => true,
        'ttl'    => 3600,
    ],

    /*
    |--------------------------------------------------------------------------
    | API
    |--------------------------------------------------------------------------
    */
    'api' => [
        'prefix'     => 'api',
        'middleware' => ['api', 'auth:sanctum'],
        'docs'       => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Ptah Forge — Component System
    |--------------------------------------------------------------------------
    |
    | Ptah Forge design system settings.
    |
    | prefix       : Blade component prefix (<x-forge-button>, etc.)
    | tailwind     : TailwindCSS version used in components
    | sidebar_items: sidebar items generated by scaffold
    |
    */
    'forge' => [
        'prefix'        => 'forge',
        'tailwind'      => 'v4',
        'sidebar_items' => [
            // Use Boxicons (bx) or FontAwesome (fas/far/fab) CSS classes:
            // ['label' => 'Dashboard', 'url' => '/dashboard', 'icon' => 'bx bx-home-alt',  'match' => 'dashboard'],
            // ['label' => 'Users',     'url' => '/users',     'icon' => 'bx bx-user',       'match' => 'users*'],
            // ['label' => 'Products',  'url' => '/products',  'icon' => 'bx bx-cube',       'match' => 'products*'],
            // ['label' => 'Settings',  'url' => '/settings',  'icon' => 'bx bx-cog',        'match' => 'settings*'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Scaffold
    |--------------------------------------------------------------------------
    */
    'scaffold' => [
        'layout'    => 'forge-dashboard',
        'auth_layout' => 'forge-auth',
    ],

    /*
    |--------------------------------------------------------------------------
    | BaseCrud
    |--------------------------------------------------------------------------
    |
    | Settings for the BaseCrud system generated by ptah:forge.
    |
    */
    'crud' => [
        'cache_enabled'  => true,
        'cache_ttl'      => 3600,
        'per_page'       => 25,
        'soft_deletes'   => true,
        'confirm_delete' => true,
        'export_driver'  => 'excel',
    ],

    /*
    |--------------------------------------------------------------------------
    | Optional Modules
    |--------------------------------------------------------------------------
    | Use `php artisan ptah:module {auth|menu|company|permissions|api|ai_agent}` to install each module.
    */
    'modules' => [
        'auth'        => env('PTAH_MODULE_AUTH', false),
        'menu'        => env('PTAH_MODULE_MENU', false),
        'company'     => env('PTAH_MODULE_COMPANY', false),
        'permissions' => env('PTAH_MODULE_PERMISSIONS', false),
        'api'         => env('PTAH_MODULE_API', false),
        'ai_agent'    => env('PTAH_MODULE_AI_AGENT', false),
    ],

    /*
    |--------------------------------------------------------------------------
    | Auth Module
    |--------------------------------------------------------------------------
    */
    'auth' => [
        'guard'               => 'web',
        'home'                => '/dashboard',
        'register_enabled'    => false,
        'two_factor'          => true,
        'remember_me'         => true,
        'session_protection'  => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Menu Module
    |--------------------------------------------------------------------------
    | driver 'config' uses sidebar_items (default, non-breaking).
    | driver 'database' reads from the menus table.
    */
    'menu' => [
        'driver'    => env('PTAH_MENU_DRIVER', 'database'),
        'cache'     => true,
        'cache_ttl' => 300,
        'max_depth' => 4,
    ],

    /*
    |--------------------------------------------------------------------------
    | Company Module
    |--------------------------------------------------------------------------
    | Company / branch management.
    | logo_disk / logo_path: where logos are stored.
    | address_fields: fields available in the address JSON.
    */
    'company' => [
        'model'          => \Ptah\Models\Company::class,
        'table'          => 'ptah_companies',
        'logo_disk'      => env('PTAH_LOGO_DISK', 'public'),
        'logo_path'      => env('PTAH_LOGO_PATH', 'company-logos'),
        'address_fields' => [
            'street', 'number', 'complement', 'district',
            'city', 'state', 'zip_code', 'country',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Permissions Module
    |--------------------------------------------------------------------------
    | Hierarchical access control system:
    | Company → Role (is_master = full bypass) → Page → Object → CRUD
    |
    | cache               : enables permission caching (highly recommended)
    | cache_ttl           : TTL in seconds
    | user_model          : host application's User model (no hard-coded FK)
    | user_id_field       : User model primary key field
    | user_query_scope    : optional Scope class to filter users shown in the
    |                       Permissions screen (e.g. only admin users)
    | company_session_key : session key for active company/branch
    | user_session_key    : session key for user id (apps without standard auth)
    | audit               : log accesses to the ptah_permission_audits table
    | audit_denied        : also log denied accesses
    | audit_master        : log accesses from users with MASTER role
    | multi_company       : user can have roles in multiple companies
    | allow_guest         : if false, guests always return false
    | admin_name          : name of the admin user created by the seeder
    | admin_email         : admin user e-mail
    | admin_password      : initial admin password (change after first login!)
    */
    'permissions' => [
        'cache'               => env('PTAH_PERMISSION_CACHE', true),
        'cache_ttl'           => (int) env('PTAH_PERMISSION_CACHE_TTL', 3600),
        'user_model'          => env('PTAH_USER_MODEL', 'App\Models\User'),
        'user_id_field'       => env('PTAH_USER_ID_FIELD', 'id'),
        // Optional Eloquent scope class applied to the user query in the
        // Permissions screen. Use this to restrict which users appear
        // (e.g. show only admin users in a project that has multiple user types).
        // Must implement \Illuminate\Database\Eloquent\Scope.
        // Example: 'user_query_scope' => App\Scopes\AdminUsersScope::class
        'user_query_scope'    => env('PTAH_USER_QUERY_SCOPE', null),
        'company_session_key' => env('PTAH_COMPANY_SESSION_KEY', 'ptah_company_id'),
        'user_session_key'    => env('PTAH_USER_SESSION_KEY', null),
        'audit'               => env('PTAH_PERMISSION_AUDIT', false),
        'audit_denied'        => env('PTAH_PERMISSION_AUDIT_DENIED', true),
        'audit_master'        => env('PTAH_PERMISSION_AUDIT_MASTER', false),
        'multi_company'       => env('PTAH_MULTI_COMPANY', true),
        'allow_guest'         => env('PTAH_PERMISSION_ALLOW_GUEST', false),
        'admin_name'          => env('PTAH_ADMIN_NAME', 'Administrador'),
        'admin_email'         => env('PTAH_ADMIN_EMAIL', 'admin@admin.com'),
        // Default password used when PTAH_ADMIN_PASSWORD is not set in .env.
        // Always change this after the first login.
        'admin_password'      => env('PTAH_ADMIN_PASSWORD', 'admin@123'),
    ],

    /*
    |--------------------------------------------------------------------------
    | AI Agent Module
    |--------------------------------------------------------------------------
    | Conversational AI widget powered by prism-php/prism.
    |
    | system_prompt : default prompt injected into every conversation.
    | max_history   : max number of messages kept per session (older ones are dropped).
    | rate_limit    : max requests per minute per session.
    | tools         : array of AiToolInterface instances to register globally.
    |                 Example: [\App\AI\Tools\MyCustomTool::class]
    |
    | Requires: composer require prism-php/prism
    | Enable  : php artisan ptah:module ai_agent
    */
    'ai_agent' => [
        'system_prompt' => env('PTAH_AI_SYSTEM_PROMPT', 'You are a helpful assistant.'),
        'max_history'   => (int) env('PTAH_AI_MAX_HISTORY', 20),
        'rate_limit'    => (int) env('PTAH_AI_RATE_LIMIT', 30),
        'tools'         => [],
    ],

];
